import { ThemeProvider } from "@/components/ThemeProvider";
import "./globals.css";
import Provider from "@/components/Provider";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { Toaster } from "sonner";
import MaxWidthWrapper from "@/components/MaxWidthWrapper";
import { Theme } from "@radix-ui/themes";
export const metadata = {
  title: "WorkEase",
  description: "Generated by create next app",
};

export default function RootLayout({ children, authModal }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <MaxWidthWrapper>
              <Theme>
                <Navbar />
                {children}
                {authModal}
                <Toaster richColors position="top-center" closeButton />
                <Footer />
              </Theme>
            </MaxWidthWrapper>
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
